add '--skip-logincheck' option: do not test for successfull login

diff --git a/watchteleboy b/watchteleboy
--- a/watchteleboy
+++ b/watchteleboy
@@ -104,6 +104,7 @@ list=false
 path=false
 record=false
 showname=false
+skiplogincheck=false
 starttime=false
 version=false
 while [ $# -gt 0 ]
@@ -121,6 +122,7 @@ do
     -t|--starttime) starttime=true; STARTTIME="$2"; shift;;
     -v|--version) version=true;;
     --deleteme) deleteme=true; DELETEME="$2"; shift;;
+    --skip-logincheck) skiplogincheck=true;;
     -*) echo "$(basename $0): error - unrecognized option '$1'" 1>&2
         echo "use '$(basename $0) --help' to get a list of available options" 1>&2
         exit 1;;
@@ -153,6 +155,7 @@ GENERAL OPTIONS:
   -c|--channel CHANNEL    specify a channel
   -h|--help               show this help and exit
   -l|--list               print a list of all channels and exit
+  --skip-logincheck       do not test if login was successfull
   -v|--version            print the version of this program
 
 OPTIONS FOR RECORDING (require -r|--record):
@@ -256,17 +259,22 @@ function cleanup {
 }
 
 # check if login was successfull
-grep "Logout" $TMPPATH/step1.html  > /dev/null
-if [ $? -eq 1 ]
-then
-  echo "failed!!!!" 1>&2
-  echo "Please check your credentials in the config file:" 1>&2
-  echo "$CONFIG" 1>&2
-  exit 1
-else
-  echo "ok"
-  touch $TMPPATH/loggedin
-  trap cleanup INT TERM EXIT
+if $skiplogincheck
+  then
+  echo "ok (forced)"
+else 
+  grep "Logout" $TMPPATH/step1.html  > /dev/null
+  if [ $? -eq 1 ]
+  then
+    echo "failed!!!!" 1>&2
+    echo "Please check your credentials in the config file:" 1>&2
+    echo "$CONFIG" 1>&2
+    exit 1
+  else
+    echo "ok"
+    touch $TMPPATH/loggedin
+    trap cleanup INT TERM EXIT
+  fi
 fi
 
 # get the station / channel list
