basic player functionality restored
* get stream_data from teleboy api
* refactored some stuff
* removed any rtmp related code

diff --git a/watchteleboy b/watchteleboy
--- a/watchteleboy
+++ b/watchteleboy
@@ -248,7 +248,7 @@ touch $TMPPATH/loggedin
 
 # remove TMPPATH dir on exit
 function cleanup {
-#  rm -rf $TMPPATH
+  rm -rf $TMPPATH
   $quiet || echo ""
 }
 trap cleanup INT TERM EXIT
@@ -286,6 +286,20 @@ else
   exit 1
 fi
 
+# Store value of session cookie (cinergy_s)
+# We only need to do that once per session and every stream request
+cinergy_s=$(grep cinergy_s $TMPPATH/cookie1 | cut -d$'\t' -f 7)
+if [ "cinergy_s" == "" ]
+then
+  echo "Could not retrieve session cookie (cinergy_s)" >&2
+  exit 1
+fi
+
+# Set teleboy api key
+# It seems that key is hard-coded, thus it didn't appear
+# necessary to retrieve its value from the web
+tb_apikey="f0e7bdfb822fa88c0c7a13f752a7e8d5c3757a13f757a13f9c0c7a13f7dfb822"
+
 # get user id
 URL="http://www.teleboy.ch/tv/player/player.php"
 rawuserdata=$(wget --user-agent "$UAGENT" \
@@ -320,6 +334,7 @@ stationlistraw="$(
     sed -e "s/%FC/ü/g"
   )"
 CHANNELS=($stationlistraw)
+
 # Check if we received something
 if [ ${#CHANNELS[@]} -gt 0 ]
 then
@@ -328,6 +343,50 @@ else
   $quiet || echo "failed"
    exit 1
 fi
+
+# Convert selected channel to station_id (sid)
+function set_sid_by_channel {
+  # ARGS:
+  # 1: CHANNEL
+  sid=$(
+    for channel in ${CHANNELS[@]}
+    do
+      echo $channel | grep -i ^$1/ | cut -d'/' -f2
+    done
+  )
+  if [[ $sid = *[!0-9]* || "$sid" = "" ]] 
+  then
+    $quiet || echo -e "\nCould not get a valid sid." 1>&2
+    exit 1
+  fi
+}
+
+# Get stream-URL from teleboy-api by providing user, session, sid
+function set_stream_data_from_api {
+  # ARGS: No
+  # The following variables need to be set
+  # CHANNEL
+  # tb_userid  (numeric user id)
+  # tb_apikey
+  # cinergy_s (session cookie)
+  set_sid_by_channel $CHANNEL
+  URL="http://tv.api.teleboy.ch/users/${tb_userid}/stream/live/${sid}?alternative=false"
+  stream_data_json=$(wget \
+  --header "x-teleboy-apikey: ${tb_apikey}" \
+  --header "x-teleboy-session: ${cinergy_s}" \
+  --output-document - \
+  --quiet \
+   "$URL")
+  stream_data_url="$(echo -e \
+    $(echo "$stream_data_json" | \
+      sed -e 's/{/\n/g' -e 's/}/\n/g' -e 's/,/\n/g' -e 's|\\||g' | \
+      grep '^"url"') | \
+      cut -d'"' -f4)"
+  stream_data_channelname="$(echo "$stream_data_json" | \
+    sed -e 's/{/\n/g' -e 's/}/\n/g' | \
+    grep '^"id"' | head -n1 | \
+    cut -d'"' -f6)"
+}
 
 # option -l|--list
 function print_channel_list {
@@ -353,131 +412,6 @@ function check_time_validity {
   fi
 }
 
-# Some functions to retrieve RTMP parameters for specified channel
-function set_sid_by_channel {
-  # ARGS:
-  # 1: CHANNEL
-  sid=$(
-    for channel in ${CHANNELS[@]}
-    do
-      echo $channel | grep -i ^$1/ | cut -d'/' -f2
-    done
-  )
-  if [[ $sid = *[!0-9]* || "$sid" = "" ]] 
-  then
-    $quiet || echo -e "\nCould not get a valid sid." 1>&2
-    exit 1
-  fi
-}
-
-# Extract sid->cid mapping json array
-URL="http://www.teleboy.ch/tv/player"
-sid2cidmap="$(
-  wget \
-    --output-document - \
-    --quiet "$URL" | \
-    grep "station2channels " | \
-    sed -e "s/\s\{1,\}TELEBOY.helpers.station2channels = {//" | \
-    sed -e "s/};//" | \
-    sed -e "s/},/}\n/g"
-  )"
-#if [ "$sid2cidmap" = "" ]
-#then
-#  $quiet || echo -e "Could not get a sid->cid map." 1>&2
-#  exit 1
-#fi
-
-function set_cids_by_sid {
-  # ARGS:
-  # 1: sid
-  channelidstring="$(
-    echo "$sid2cidmap" | \
-      grep ^\"${1}\" | \
-      sed -e 's/"//g' | \
-      cut -d "{" -f2 | \
-      cut -d "}" -f1 | \
-      sed -e "s/,/\n/g" | \
-      sort | \
-      cut -d":" -f2
-    )"
-  cid=$(echo "$channelidstring" | head -n1)
-  cid2=$(echo "$channelidstring" | tail -n+2)
-  # cid2 points to stream with origaudio.
-  # Do ORIGAUDIO selection:
-  if $ORIGAUDIO && [ "$cid2" != "" ]
-  then
-    cid=$cid2
-  fi
-  if [[ $cid = *[!0-9]* || "$cid" = "" ]]
-  then
-    $quiet || echo -e "\nCould not get a valid cid." 1>&2
-    exit 1
-  fi
-}
-
-function set_rtmpparams_by_cids {
-  # ARGS:
-  # 1: cid
-  # set profile by parsing channel name. Profile correlates with video resolutin
-  echo "$CHANNEL" | grep -i 'HD$' > /dev/null && profile="P6" || profile="high"
-  URL="http://www.teleboy.ch/tv/player/ajax/liveChannelParams?cid=${1}&profile=${profile}"
-  rtmpparamjson="$(wget \
-    --quiet \
-    --output-document - \
-    --load-cookies ${TMPPATH}/cookie1 \
-    $URL )"
-  rtmpparamstring=$(echo -e "$rtmpparamjson" | cut -d'"' -f16 | sed -e 's|\\||g')
-  OIFS=$IFS
-  IFS="|"
-  rtmpparams=($rtmpparamstring)
-  IFS=$OIFS
-  # check success
-  success=$(echo "$rtmpparamjson" | cut -d':' -f2 | cut -d',' -f1)
-  if [ "$success" != "true" ]
-  then 
-    echo -e "\nCouldn't get rtmp parameters" 1>&2
-    return 1
-  fi
-  rtmpparams[2]=$(echo "$rtmpparamjson" | cut -d'"' -f8)
-}
-
-function dump_rtmp_stream {
-  # ARGS:
-  # 1: channel
-  # 2: output file
-  [ -d $TMPPATH ] || exit 1
-  set_sid_by_channel "$1"
-  set_cids_by_sid "$sid"
-  set_rtmpparams_by_cids "$cid" "$cid2" || return 1
-  # Things with params work different now. Don't know of ORIGAUDIO
-  # still works.
-  ## switch to original audio channel (if configured)
-  ## When rtmpparams for given channel has 21 elements instead
-  ## of 11, this means there is an alternativ (original audio)
-  ## stream available.
-  #if $ORIGAUDIO && [ ${#rtmpparams[@]} -eq 21 ]
-  #then
-  #  paramshift=10
-  #else 
-  #  paramshift=0
-  #fi
-  
-  channame="${rtmpparams[2]}"
-  playpath="${rtmpparams[0]}"
-  url="${rtmpparams[1]}"
-
-  # show channel name
-  $quiet || echo -e "${channame}" | iconv -f latin1
-
-  # rtmpdump command
-  rtmpdump \
-    --rtmp "$url" \
-    --playpath "$playpath" \
-    --quiet \
-    --flv "$2" 2> /dev/null &
-  PID=$!
-}
-
 # test channel input validity
 function channel_validity {
   # ARGS:
@@ -495,6 +429,7 @@ function channel_validity {
     return 1
   fi
 }
+
 
 # interface appearance
 function set_ui_window_params {
@@ -862,6 +797,13 @@ fi
 
 # Compose mplayer command
 MPLAYER="mplayer $MPLAYEROPTS "
+function play_http_stream {
+  # ARGS: None
+  # Required variables:
+  # stream_data_url
+  $MPLAYER -vid 4 "${stream_data_url}"
+}
+
 
 # Compose rmtpdump output filename
 function compose_outfile {
@@ -883,30 +825,14 @@ function compose_outfile {
 function player_recorder {
   # ARGS:
   # 1: Channel
+  set_stream_data_from_api
   compose_outfile $1
   if $record
   then
-    dump_rtmp_stream $1 "$OUTFILE" || return 1
+    dump_http_stream $1 "$OUTFILE" || return 1
   else
     # Make sure there is an empty OUTFILE 
-    > "$OUTFILE"
-    dump_rtmp_stream $1 "$OUTFILE" || return 1
-    # Only start mplayer after having downloaded BUFFER bytes
-    # We need a higher buffer for HD streams to start correctly
-    [ $profile == "P6"  ] && BUFFER=$HDBUFFER || BUFFER=$SDBUFFER
-    while [  "$(du -b "$OUTFILE" | cut -f1)" -lt "$BUFFER" ]
-    do
-      sleep 0.5
-      if ! kill -0 $PID 2> /dev/null
-      then
-        code=$(wait $PID; echo $?)
-        echo "rtmpdump returned an error code: $code" 1>&2
-        sleep 2
-        return 1
-      fi
-    done
-    $MPLAYER $TMPPATH/stream.flv 2> /dev/null
-    kill $PID
+    play_http_stream || return 1
   fi
 }
 
