new implementation for retrieving channels

diff --git a/watchteleboy b/watchteleboy
--- a/watchteleboy
+++ b/watchteleboy
@@ -283,50 +283,30 @@ else
   fi
 fi
 
-# get the station / channel list
+# get the channel list
+# CHANNELS is an array containing an element per station
+# Each element follows this format:
+# STATIONNAME/STATIONID
+# Later on, the STATIONID (sid) is mapped to two channel ids: cid, cid2
+# Those again are used to request the proper RTMP parameters for the
+# desired station.
 $quiet || echo -n "receive channel list..."
-POST="cmd=getStations&category=${CHANSELECTION}"
-URL="http://www.teleboy.ch/tv/player/includes/ajax.php"
-wget --user-agent "$UAGENT" \
-    --quiet \
-    --load-cookies $TMPPATH/cookie1 \
-    --post-data $POST \
-    --output-document $TMPPATH/stations.html.latin1 \
-    $URL
-iconv -f LATIN1 -t UTF-8 $TMPPATH/stations.html.latin1 > $TMPPATH/stations.html
-# Check if current user has answered all questions on teleboy.ch
-if ! grep "getLiveChannelData" $TMPPATH/stations.html > /dev/null 
+URL="http://www.teleboy.ch/programm/?program_date=live"
+stationlistraw="$(
+  wget --output-document - \
+    --user-agent "$UAGENT" \
+    --quiet $URL | \
+    grep "<tr class=\"playable blackListing\">"  | \
+    cut -d"/" -f4,5)"
+CHANNELS=($stationlistraw)
+# Check if we received something
+if [ ${#CHANNELS[@]} -gt 0 ]
 then
-  echo "failed"
-  echo ""
-  echo "The user '$USER' is not fully configured for watching streams."
-  echo "Please log in to http://www.teleboy.ch and click the 'Live TV' tab."
-  echo "Please fill out the form. If you're able to watch streams in the"
-  echo "browser, check again with watchteleboy."
-  exit 1
+  $quiet || echo "ok (${#CHANNELS[@]} channels)"
+else
+  $quiet || echo "failed"
+   exit 1
 fi
-channelnames=$(grep -e " <img.*src=\"/img/station/.*/logo" $TMPPATH/stations.html | cut -d'"' -f8)
-channelids=$(grep "javascript:getLiveChannelData" $TMPPATH/stations.html | cut -d "(" -f 2 | cut -d ")" -f1 | sed -e 's/,//g')
-CHANNELS=$(paste -d' ' \
-  <(echo "$channelnames" | \
-    sed -e '
-      s/ //g
-      s/\.//g
-      s/+/plus/g
-      s/Ô/O/g
-    ' | head -n $(echo "$channelids" | wc -l)) \
-  <(echo "$channelids"))
-$quiet || echo "done"
-CHANNELS="
-$(echo "$CHANNELS" | grep -iv euronews)
-SF1_o 159 0
-SFzwei_o 108 0
-Arte_fr 161 20
-EuroNews_de 216 0
-EuroNews_fr 158 0
-EuroNews_it 217 0
-EuroNews_en 45 0
-"
 
 # option -l|--list
 if $list
