added alternative endtime_dialog

diff --git a/watchteleboy b/watchteleboy
--- a/watchteleboy
+++ b/watchteleboy
@@ -525,28 +525,44 @@ function starttime_dialog {
 function endtime_dialog {
   while true
   do
-    set_ui_window_params 2
-    endtimeinit=$(( $(date -d "$STARTTIME" +%s) + 3600 ))
-    ENDTIME=$(whiptail \
-      --title "$TITLE" \
-      --inputbox "\nStop recording at:" \
-      $BOXWIDTH $BOXHEIGHT "$(date -d @${endtimeinit} '+%Y-%m-%d %H:%M')" \
-      3>&2 2>&1 1>&3 )
-    [ "$?" != "0" ] && exit 0;
+    if $whiptail
+    then
+      set_ui_window_params 2
+      endtimeinit=$(( $(date -d "$STARTTIME" +%s) + 3600 ))
+      ENDTIME=$(whiptail \
+	--title "$TITLE" \
+	--inputbox "\nStop recording at:" \
+	$BOXWIDTH $BOXHEIGHT "$(date -d @${endtimeinit} '+%Y-%m-%d %H:%M')" \
+	3>&2 2>&1 1>&3 )
+      [ "$?" != "0" ] && exit 0;
+    else
+      echo -n "Stop recording at: "
+      read ENDTIME
+    fi
     if date -d "$ENDTIME" > /dev/null 2>&1
     then
       if [ $(date -d "$ENDTIME" +%s) -lt $(date -d "$STARTTIME" +%s) ]
       then
-        whiptail --title "$TITLE" --msgbox \
-          " The specified time:\n\n    ${ENDTIME}\n\nis before start time ($STARTTIME)." \
-          $BOXWIDTH $BOXHEIGHT
+        if $whiptail
+        then
+	  whiptail --title "$TITLE" --msgbox \
+	    " The specified time:\n\n    ${ENDTIME}\n\nis before start time ($STARTTIME)." \
+	    $BOXWIDTH $BOXHEIGHT
+         else
+           echo -e "The specified time:\n    ${ENDTIME}\nis before start time ($STARTTIME)."
+         fi
       else
         break
       fi
     else
-      whiptail --title "$TITLE" --msgbox \
-        " The specified time:\n\n    ${ENDTIME}\n\ncould not be parsed." \
-        $BOXWIDTH $BOXHEIGHT
+      if $whiptail
+      then
+	whiptail --title "$TITLE" --msgbox \
+	  " The specified time:\n\n    ${ENDTIME}\n\ncould not be parsed." \
+	  $BOXWIDTH $BOXHEIGHT
+      else
+        echo -e "The specified time:\n    ${ENDTIME}\ncould not be parsed."
+      fi
     fi
   done
 }
